### ISSUE TITLE
Is the space size, configurable?

### ISSUE THREAD

**Issue by patchthecode** [malkouz/MKMagneticProgress#2]
<img width="196" alt="screen shot 2017-09-12 at 2 17 33 pm" src="https://user-images.githubusercontent.com/2439146/30348779-690a5b72-97c5-11e7-812a-9955143970ea.png">

**Comment by malkouz** [comment]
Next week I will push a new release with resolving this issue and supporting Swift 4 with iOS 11

**Comment by patchthecode** [comment]
alright. i guess you'll let me know when.
This is the only thing i think thats missing from this lib. The space is too wide.

**Comment by malkouz** [comment]
Sure, I will notify you when it available.

Thank you for your contribution :wink:

**Comment by malkouz** [comment]
hey patchthecode

check it now, please

**Comment by patchthecode** [comment]
awesome man. it works.
the only change i did was i commented out this line

```swift
    @IBInspectable open var spaceDegree: CGFloat = 45.0 {
        didSet {
//            if spaceDegree < 45.0{
//                spaceDegree = 45.0
//            }
```

As i needed my circle gap to be smaller.
cheers 🍻

**Comment by malkouz** [comment]
:+1:
